import type { Message } from '../../types';
import { parseExternalMessageId, type WhatsAppTransport } from '../../integrations/whatsapp/provider';

export type MessageCapabilities = {
  transport: WhatsAppTransport | null;
  canReact: boolean;
  canEdit: boolean;
  canRevoke: boolean;
};

export type ProviderMessageMutationCapabilities = {
  edit: 'supported' | 'unsupported' | 'unknown';
  revoke: 'supported' | 'unsupported' | 'unknown';
};

// The source id is generated by the bridge and is the authoritative transport
// for a message. This matters for hybrid inboxes, where the inbox default may
// differ from the provider that actually sent this particular message.
export const transportForMessage = (message: Pick<Message, 'sourceId' | 'whatsappTransport'>): WhatsAppTransport | null =>
  parseExternalMessageId(message.sourceId)?.provider || (message.sourceId?.startsWith('wamid.') ? 'meta_cloud' : null) || message.whatsappTransport || null;

export const capabilitiesForMessage = (message: Message, providerCapabilities?: ProviderMessageMutationCapabilities | null): MessageCapabilities => {
  const transport = transportForMessage(message);
  const hasExternalTarget = Boolean((message.sourceId && parseExternalMessageId(message.sourceId)) || message.sourceId?.startsWith('wamid.'));
  const canMutate = hasExternalTarget && !message.isPrivate && !message.isActivity && !message.isRevoked;
  const isOwnWhatsAppMessage = message.sender === 'me' && message.whatsappFromMe !== false;

  return {
    // All configured transports support WhatsApp reactions, but a local/note
    // message without the original external identity must never expose it.
    transport,
    canReact: canMutate && transport !== null,
    // Unknown capability is deliberately permissive. The provider response,
    // not message age or incomplete historical metadata, decides the result.
    canEdit: canMutate && isOwnWhatsAppMessage && Boolean(message.text?.trim()) && providerCapabilities?.edit !== 'unsupported',
    canRevoke: canMutate && isOwnWhatsAppMessage && providerCapabilities?.revoke !== 'unsupported',
  };
};
