import { createTrackId, type UnifiedWhatsAppEvent } from './track.js';
import { normalizeBrazilianPhone } from '../phone.ts';

const record = (value: unknown): Record<string, unknown> => value && typeof value === 'object' ? value as Record<string, unknown> : {};
const string = (value: unknown) => typeof value === 'string' && value ? value : undefined;
const time = (value: unknown) => typeof value === 'number' ? new Date(value * 1000).toISOString() : typeof value === 'string' ? value : new Date().toISOString();
export type WahaMediaKind = 'image' | 'audio' | 'video' | 'document';
export interface IncomingWahaMessage extends UnifiedWhatsAppEvent { externalId: string; session: string; chatId: string; fromMe: boolean; remoteJid: string; sourceId: string; name: string; contactName?: string; groupName?: string; avatarUrl?: string; phoneNumber?: string; lid?: string; chatType: 'private' | 'group'; participantJid?: string; participantName?: string; content: string; quotedMessageId?: string; quotedMetadata?: Record<string, unknown>; media?: { kind: WahaMediaKind; url?: string; data?: string; mimetype?: string; filename?: string }; ack?: number; }
export interface IncomingWahaReaction extends UnifiedWhatsAppEvent { session: string; targetMessageId: string; chatId: string; senderId: string; emoji: string; fromMe: boolean; participantJid?: string; }
export interface IncomingWahaMutation extends UnifiedWhatsAppEvent { session: string; targetMessageId: string; chatId: string; content?: string; }
export interface IncomingWahaGroupLifecycle extends UnifiedWhatsAppEvent { session: string; groupId: string; subject?: string; description?: string; avatarUrl?: string; participants?: Array<{ jid: string; name?: string; phoneNumber?: string; admin?: string | null }>; participantAction?: 'add' | 'remove' | 'promote' | 'demote'; }
const phoneFor = (jid: string) => jid.match(/^(\d{8,15})@(c\.us|s\.whatsapp\.net)$/)?.[1];
// WAHA may identify the same message with different chat identities in a
// message event and its ACK (for example @c.us vs @lid). The final token is
// the WhatsApp message key; use it as the provider identity everywhere while
// continuing to accept older full WAHA IDs already persisted in Chatwoot.
export const normalizeWahaMessageId = (value: string) => {
  const match = /^(?:true|false)_[^_]+_([^_]+)(?:_[^_]+)?$/i.exec(value);
  return match?.[1] || value;
};
// Keep the JID intact in the ContactInbox source id. The HTTP client escapes
// it once when building the public Chatwoot URL; escaping here as well turns
// `@` into `%2540` and prevents the ContactInbox from being found.
// ContactInbox source IDs are stored unescaped. The HTTP client escapes this
// value only when it becomes part of a route; escaping here would create a
// second identity for the same `@g.us` group.
export const wahaGroupSourceId = (jid: string) => `whatsapp:group:${jid}`;
const mediaFor = (payload: Record<string, unknown>): IncomingWahaMessage['media'] => { const media = record(payload.media); const mimetype = string(media.mimetype) || string(payload.mimetype); const type = string(media.type) || string(payload.type) || mimetype || ''; const kind: WahaMediaKind | null = /image/i.test(type) ? 'image' : /audio|ptt|voice/i.test(type) ? 'audio' : /video/i.test(type) ? 'video' : payload.hasMedia === true ? 'document' : null; return kind ? { kind, ...(string(media.url) ? { url: string(media.url) } : {}), ...(string(media.data) ? { data: string(media.data) } : {}), ...(mimetype ? { mimetype } : {}), ...(string(media.filename) || string(payload.filename) ? { filename: string(media.filename) || string(payload.filename) } : {}) } : undefined; };

export const parseWahaWebhook = (payload: unknown): UnifiedWhatsAppEvent => { const root = record(payload); const event = string(root.event) || string(root.type) || 'unknown'; const data = record(root.payload || root.data); return { trackId: createTrackId(), transport: 'waha', event, category: event.split('.')[0] || 'unknown', type: event, timestamp: time(data.timestamp), ...(string(root.session) ? { session: string(root.session) } : {}), ...(string(data.id) ? { externalId: string(data.id) } : {}), ...(string(data.chatId) || string(data.from) ? { chatId: string(data.chatId) || string(data.from) } : {}), ...(data.fromMe === true ? { fromMe: true } : {}) }; };

export const parseIncomingWahaMessage = (payload: unknown): IncomingWahaMessage | null => { const base = parseWahaWebhook(payload); if (base.event !== 'message' && base.event !== 'message.any') return null; const root = record(payload); const data = record(root.payload || root.data); const rawExternalId = string(data.id); const session = string(root.session); const fromMe = data.fromMe === true; // GOWS history records own messages with `from` set to the remote chat and `to: null`.
  const chatId = string(data.chatId) || string(data.from) || string(data.to); if (!rawExternalId || !session || !chatId || chatId === 'status@broadcast') return null; const externalId = normalizeWahaMessageId(rawExternalId); const chatType = chatId.endsWith('@g.us') ? 'group' : 'private'; const identity = chatType === 'group' ? chatId : (fromMe ? string(data.to) || string(data.from) || chatId : string(data.from) || chatId); const rawPhone = phoneFor(identity); const phone = rawPhone ? normalizeBrazilianPhone(rawPhone) : undefined; const lid = identity.endsWith('@lid') ? identity.slice(0, -4) : undefined; const contactName = string(data.notifyName) || string(data.pushName); const chat = record(data.chat); const groupName = string(data.subject) || string(data.groupSubject) || string(data.chatName) || string(chat.subject) || string(chat.name); const quoted = record(data.replyTo || data.quotedMsg || data.quotedMessage); const unresolved = Object.keys(quoted).length ? { participant: string(quoted.participant), body: string(quoted.body), has_media: quoted.hasMedia === true, ...(mediaFor(quoted) ? { media: mediaFor(quoted) } : {}) } : undefined; return { ...base, externalId, session, chatId, remoteJid: chatId, fromMe, sourceId: chatType === 'group' ? wahaGroupSourceId(chatId) : `whatsapp:${phone || `lid:${lid || identity}`}`, name: chatType === 'group' ? groupName || chatId : contactName || `+${phone || lid || identity}`, ...(chatType === 'private' && contactName ? { contactName } : {}), ...(chatType === 'group' && groupName ? { groupName } : {}), ...(phone ? { phoneNumber: `+${phone}` } : {}), ...(lid ? { lid } : {}), chatType, ...(string(data.participant) ? { participantJid: string(data.participant) } : {}), ...(string(data.participantName) || contactName ? { participantName: string(data.participantName) || contactName } : {}), content: string(data.body) || string(data.text) || '', ...(string(quoted.id) ? { quotedMessageId: normalizeWahaMessageId(string(quoted.id)!) } : {}), ...(unresolved ? { quotedMetadata: unresolved } : {}), ...(mediaFor(data) ? { media: mediaFor(data) } : {}), ...(typeof data.ack === 'number' ? { ack: data.ack } : {}) }; };

// The history API returns the same normalized WAHA message object used by
// webhooks, but without the event envelope. Keeping this adapter here means
// identity, LID, groups, media and reply parsing cannot drift from realtime.
export const parseWahaHistoryMessage = (session: string, message: unknown): IncomingWahaMessage | null =>
  parseIncomingWahaMessage({ event: 'message.any', session, payload: message });
export const parseIncomingWahaReaction = (payload: unknown): IncomingWahaReaction | null => { const base = parseWahaWebhook(payload); if (base.event !== 'message.reaction') return null; const root = record(payload); const data = record(root.payload || root.data); const reaction = record(data.reaction); const rawTargetMessageId = string(data.msgId) || string(data.messageId) || string(reaction.messageId); const session = string(root.session); const chatId = string(data.chatId) || string(data.from); if (!rawTargetMessageId || !session || !chatId) return null; return { ...base, session, targetMessageId: normalizeWahaMessageId(rawTargetMessageId), chatId, senderId: string(data.senderId) || string(data.participant) || (data.fromMe === true ? 'self' : `contact:${chatId}`), emoji: string(reaction.text) || string(reaction.emoji) || string(data.emoji) || '', fromMe: data.fromMe === true, ...(string(data.participant) ? { participantJid: string(data.participant) } : {}) }; };
export const parseIncomingWahaMutation = (payload: unknown): IncomingWahaMutation | null => { const base = parseWahaWebhook(payload); if (base.event !== 'message.edited' && base.event !== 'message.revoked') return null; const root = record(payload); const data = record(root.payload || root.data); const after = record(data.after); const rawTargetMessageId = base.event === 'message.edited' ? (string(data.editedMessageId) || string(data.messageId) || string(after.id)) : (string(data.revokedMessageId) || string(data.messageId) || string(after.id)); const session = string(root.session); const chatId = string(data.chatId) || string(data.from); if (!rawTargetMessageId || !session || !chatId) return null; return { ...base, session, targetMessageId: normalizeWahaMessageId(rawTargetMessageId), chatId, ...(string(data.body) || string(after.body) ? { content: string(data.body) || string(after.body) } : {}) }; };

export const parseIncomingWahaGroupLifecycle = (payload: unknown): IncomingWahaGroupLifecycle | null => {
  const base = parseWahaWebhook(payload); if (!['group.v2.join', 'group.v2.leave', 'group.v2.participants', 'group.v2.update'].includes(base.event)) return null;
  const root = record(payload); const data = record(root.payload || root.data); const group = record(data.group || data); const session = string(root.session); const groupId = string(group.id) || string(data.groupId) || string(data.chatId);
  if (!session || !groupId || !groupId.endsWith('@g.us')) return null;
  const actionValue = string(data.action) || string(group.action);
  const participantAction = actionValue === 'join' ? 'add' : actionValue === 'leave' ? 'remove' : actionValue === 'promote' ? 'promote' : actionValue === 'demote' ? 'demote' : undefined;
  const rawParticipants = Array.isArray(group.participants) ? group.participants : Array.isArray(data.participants) ? data.participants : [];
  const participants = rawParticipants.flatMap((item): Array<{ jid: string; name?: string; phoneNumber?: string; admin?: string | null }> => {
    const value = record(item); const jid = string(value.id) || string(value.jid) || (typeof item === 'string' ? item : undefined); if (!jid) return [];
    const phoneNumber = phoneFor(jid); const role = string(value.role) || string(value.admin); return [{ jid, ...(string(value.name) || string(value.pushName) ? { name: string(value.name) || string(value.pushName) } : {}), ...(phoneNumber ? { phoneNumber } : {}), ...(role ? { admin: role } : {}) }];
  });
  return { ...base, session, groupId, ...(string(group.subject) || string(group.name) ? { subject: string(group.subject) || string(group.name) } : {}), ...(string(group.description) ? { description: string(group.description) } : {}), ...(string(group.pictureUrl) || string(group.avatarUrl) ? { avatarUrl: string(group.pictureUrl) || string(group.avatarUrl) } : {}), ...(participants.length ? { participants } : {}), ...(participantAction ? { participantAction } : {}) };
};
