import { useEffect, useState } from 'react';
import { X } from 'lucide-react';
import type { AgentPermissionAssignment, AssignableAgent, PermissionProfile } from '../domain/currentUser';
import { inboxService } from '../integrations/chatwoot/inboxes';

export const AgentInboxPermissionsModal = ({ accountId, agent, onClose, isDarkMode }: { accountId: number; agent: AssignableAgent; onClose: () => void; isDarkMode: boolean }) => {
  const [profiles, setProfiles] = useState<PermissionProfile[]>([]);
  const [assignment, setAssignment] = useState<AgentPermissionAssignment | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([inboxService.listPermissionProfiles(accountId), inboxService.getAgentPermissionAssignment(accountId, agent.id)]).then(([items, value]) => { setProfiles(items); setAssignment(value); }).catch(() => setError('Não foi possível carregar as permissões do agente.')); }, [accountId, agent.id]);
  const profileName = (id: number | null) => profiles.find(profile => profile.id === id)?.name || 'Agente (padrão)';
  const save = async () => { if (!assignment) return; setSaving(true); try { await inboxService.saveAgentPermissionAssignment(accountId, agent.id, assignment); onClose(); } catch { setError('Não foi possível salvar as permissões.'); } finally { setSaving(false); } };
  const style = isDarkMode ? 'bg-[#182228] text-white border-[#2a3942]' : 'bg-white text-[#111b21] border-[#d1d7db]';
  return <div className="fixed inset-0 z-[130] grid place-items-center bg-black/70 p-4"><div className={`w-full max-w-lg rounded-2xl border p-5 ${style}`}><div className="flex justify-between"><div><h3 className="font-bold">Inboxes e permissões · {agent.name}</h3><p className="mt-1 text-xs text-[#8696a0]">Cada caixa pode usar um perfil diferente.</p></div><button type="button" onClick={onClose}><X className="w-4 h-4" /></button></div>{error && <p className="mt-3 text-xs text-red-400">{error}</p>}{!assignment ? <p className="py-8 text-center text-xs text-[#8696a0]">Carregando…</p> : <><label className="mt-5 block text-xs font-bold">Permissões gerais<select value={assignment.permissionProfileId || ''} onChange={event => setAssignment({ ...assignment, permissionProfileId: event.target.value ? Number(event.target.value) : null })} className="mt-1.5 w-full rounded-lg border p-2 text-sm text-black"><option value="">Agente (padrão)</option>{profiles.map(profile => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><div className="mt-5 space-y-3">{assignment.inboxes.map(inbox => <label key={inbox.inboxId} className="block rounded-xl border p-3 text-xs"><span className="font-bold">{inbox.inboxName}</span><select value={inbox.permissionProfileId || ''} onChange={event => setAssignment({ ...assignment, inboxes: assignment.inboxes.map(item => item.inboxId === inbox.inboxId ? { ...item, permissionProfileId: event.target.value ? Number(event.target.value) : null } : item) })} className="mt-2 w-full rounded-lg border p-2 text-sm text-black"><option value="">Agente (padrão)</option>{profiles.map(profile => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select><span className="mt-1 block text-[#8696a0]">Atual: {profileName(inbox.permissionProfileId)}</span></label>)}</div><div className="mt-5 flex justify-end"><button type="button" disabled={saving} onClick={() => void save()} className="rounded-lg bg-[#00a884] px-4 py-2 text-xs font-bold text-white">{saving ? 'Salvando…' : 'Salvar permissões'}</button></div></>}</div></div>;
};
