import React, { useEffect, useMemo, useState } from 'react';
import { ExternalLink, Folder, Plus, Settings, ToggleLeft, ToggleRight, X } from 'lucide-react';
import { dashboardApps, type DashboardApp } from '../features/apps/dashboardApps';
import {
  DASHBOARD_APP_SANDBOX,
  isAllowedDashboardAppUrl,
  nextEmbedStatus,
  type EmbedStatus,
} from '../features/apps/embedPolicy';

interface Props { onClose: () => void; accountId: number | null; canManage?: boolean; isDarkMode?: boolean; }
export const AppsView: React.FC<Props> = ({ onClose, accountId, canManage = false, isDarkMode = true }) => {
  const [apps, setApps] = useState<DashboardApp[]>([]); const [selected, setSelected] = useState<DashboardApp | null>(null); const [editing, setEditing] = useState<DashboardApp | 'new' | null>(null); const [title, setTitle] = useState(''); const [url, setUrl] = useState(''); const [enabled, setEnabled] = useState(true); const [error, setError] = useState(''); const [embedStatus, setEmbedStatus] = useState<EmbedStatus>('loading');
  const visibleApps = useMemo(() => canManage ? apps : apps.filter((app) => app.enabled), [apps, canManage]);
  const reload = async () => { if (!accountId) return; try { setApps(await dashboardApps.list(accountId)); } catch { setError('Não foi possível carregar os aplicativos desta conta.'); } };
  useEffect(() => { setSelected(null); setEditing(null); void reload(); }, [accountId]);
  useEffect(() => { setEmbedStatus('loading'); }, [selected?.id]);
  const edit = (app: DashboardApp | 'new') => { setEditing(app); setTitle(app === 'new' ? '' : app.title); setUrl(app === 'new' ? '' : app.content[0]?.url || ''); setEnabled(app === 'new' ? true : app.enabled); setError(''); };
  const save = async () => { if (!accountId || !title.trim() || !isAllowedDashboardAppUrl(url, import.meta.env.DEV)) { setError('Informe um nome e uma URL HTTPS válida.'); return; } try { const input = { title: title.trim(), url, enabled }; const app = editing === 'new' ? await dashboardApps.create(accountId, input) : await dashboardApps.update(accountId, editing!.id, input); setApps((old) => editing === 'new' ? [...old, app] : old.map((item) => item.id === app.id ? app : item)); setSelected(app); setEditing(null); } catch { setError('Não foi possível salvar o aplicativo.'); } };
  const remove = async (app: DashboardApp) => { if (!accountId || !window.confirm(`Excluir ${app.title}?`)) return; await dashboardApps.remove(accountId, app.id); setApps((old) => old.filter((item) => item.id !== app.id)); if (selected?.id === app.id) setSelected(null); };
  const toggle = async (app: DashboardApp) => { if (!accountId) return; const updated = await dashboardApps.update(accountId, app.id, { title: app.title, url: app.content[0]?.url || '', enabled: !app.enabled }); setApps((old) => old.map((item) => item.id === updated.id ? updated : item)); setSelected((old) => old?.id === updated.id ? updated : old); };
  const selectedUrl = selected?.content[0]?.url ?? '';
  const isSafeEmbedUrl = isAllowedDashboardAppUrl(selectedUrl, import.meta.env.DEV);
  return <div className={`flex flex-1 min-w-0 flex-col md:flex-row ${isDarkMode ? 'bg-[#151717] text-white' : 'bg-white text-[#111b21]'}`}>
    <aside className="w-full shrink-0 border-b border-[#242525] p-3 md:w-80 md:border-b-0 md:border-r"><header className="flex items-center justify-between"><span className="flex items-center gap-2 font-bold"><Folder className="text-[#00a884]" />Apps</span><button aria-label="Voltar para conversas" onClick={onClose}><X /></button></header>{canManage && <button type="button" onClick={() => edit('new')} className="mt-3 w-full rounded-lg bg-[#00a884] px-3 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-4 w-4" />Adicionar app</button>}<div className="mt-3 space-y-1">{visibleApps.length === 0 && <p className="p-4 text-center text-xs text-[#8696a0]">Nenhum app disponível nesta conta.</p>}{visibleApps.map((app) => <div key={app.id} className={`flex items-center gap-1 rounded-lg p-2 ${selected?.id === app.id ? 'bg-[#00a884]/15' : ''}`}><button type="button" onClick={() => setSelected(app)} className="min-w-0 flex-1 text-left"><b className="block truncate text-sm">{app.title}</b>{canManage && !app.enabled && <span className="text-[10px] text-[#8696a0]">Desativado</span>}</button>{canManage && <><button type="button" title={app.enabled ? 'Desativar' : 'Ativar'} onClick={() => void toggle(app)}>{app.enabled ? <ToggleRight className="text-[#00a884]" /> : <ToggleLeft />}</button><button type="button" aria-label={`Editar ${app.title}`} onClick={() => edit(app)}><Settings className="h-4 w-4" /></button><button type="button" aria-label={`Excluir ${app.title}`} onClick={() => void remove(app)}><X className="h-4 w-4" /></button></>}</div>)}</div></aside>
    <main className="min-h-0 min-w-0 flex-1 flex flex-col">{editing && <div className="m-auto w-full max-w-md space-y-3 rounded-xl border p-5"><h3 className="font-bold">{editing === 'new' ? 'Adicionar app' : 'Editar app'}</h3><input aria-label="Nome do aplicativo" value={title} onChange={(event) => setTitle(event.target.value)} className="w-full rounded border p-2 text-black" placeholder="Nome" /><input aria-label="URL do aplicativo" value={url} onChange={(event) => setUrl(event.target.value)} className="w-full rounded border p-2 text-black" placeholder="https://app.exemplo.com" /><label className="flex gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} />Disponível para agentes</label>{error && <p role="alert" className="text-xs text-red-400">{error}</p>}<button type="button" onClick={() => void save()} className="rounded bg-[#00a884] px-3 py-2 text-xs font-bold text-white">Salvar</button></div>}{!editing && selected && selectedUrl && <><header className="flex items-center justify-between border-b p-3"><div><b>{selected.title}</b><p className="text-xs text-[#8696a0]">Aplicativo incorporado</p></div>{isSafeEmbedUrl && <a href={selectedUrl} target="_blank" rel="noopener noreferrer" aria-label="Abrir em nova aba"><ExternalLink /></a>}</header>{!isSafeEmbedUrl ? <div className="p-3 text-xs">A URL deste aplicativo não é permitida.</div> : embedStatus === 'blocked' ? <div className="flex items-center justify-between border-b p-3 text-xs"><span>Este aplicativo não permite abertura incorporada.</span><a href={selectedUrl} target="_blank" rel="noopener noreferrer" className="font-bold text-[#00a884]">Abrir em nova aba</a></div> : <div className="relative min-h-0 flex-1">{embedStatus === 'loading' && <div role="status" className="absolute inset-0 z-10 flex items-center justify-center bg-white text-xs text-[#667781]">Carregando aplicativo…</div>}<iframe title={selected.title} src={selectedUrl} sandbox={DASHBOARD_APP_SANDBOX} referrerPolicy="strict-origin-when-cross-origin" onLoad={() => setEmbedStatus(nextEmbedStatus('load'))} onError={() => setEmbedStatus(nextEmbedStatus('error'))} className="h-full w-full border-0 bg-white" /></div>}</>}{!editing && !selected && <div className="m-auto text-center text-[#8696a0]"><Folder className="mx-auto mb-3" />Selecione um aplicativo para abrir.</div>}</main>
  </div>;
};
