import React, { useEffect, useMemo, useState } from 'react';
import { Check, Loader2, Search, UserPlus, X } from 'lucide-react';
import { groupCreationClient, type GroupCreationContact } from '../features/groups/creation';

interface Props { accountId: number; selected: GroupCreationContact[]; onChange: (contacts: GroupCreationContact[]) => void; memberPhones?: string[]; memberContactIds?: number[]; isDarkMode?: boolean; }
const digits = (value: string) => value.replace(/\D/g, '');
export const GroupContactSelector: React.FC<Props> = ({ accountId, selected, onChange, memberPhones = [], memberContactIds = [], isDarkMode = false }) => {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<GroupCreationContact[]>([]); const [searching, setSearching] = useState(false);
  const [creating, setCreating] = useState(false); const [newName, setNewName] = useState(''); const [error, setError] = useState<string | null>(null);
  const selectedIds = useMemo(() => new Set(selected.map(item => item.id)), [selected]); const members = useMemo(() => new Set(memberPhones.map(digits).filter(Boolean)), [memberPhones]); const memberIds = useMemo(() => new Set(memberContactIds), [memberContactIds]);
  const typedPhone = digits(query); const exactExists = results.some(contact => digits(contact.phoneNumber) === typedPhone); const canCreate = /^\d{8,15}$/.test(typedPhone) && !exactExists;
  useEffect(() => { const controller = new AbortController(); const value = query.trim(); if (value.length < 2) { setResults([]); setSearching(false); return () => controller.abort(); } setSearching(true); const timer = window.setTimeout(() => groupCreationClient.searchContacts(accountId, value, controller.signal).then(data => setResults(data.contacts)).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : 'Falha na busca.'); }).finally(() => !controller.signal.aborted && setSearching(false)), 300); return () => { window.clearTimeout(timer); controller.abort(); }; }, [accountId, query]);
  const create = async () => { if (!newName.trim() || !canCreate) return; setSearching(true); setError(null); try { const { contact } = await groupCreationClient.createContact({ accountId, name: newName.trim(), phoneNumber: `+${typedPhone}` }); onChange(selectedIds.has(contact.id) ? selected : [...selected, contact]); setQuery(''); setNewName(''); setCreating(false); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao criar contato.'); } finally { setSearching(false); } };
  const field = isDarkMode ? 'bg-[#202c33] border-[#2a3942] text-white' : 'bg-gray-50 border-gray-300 text-[#111b21]';
  return <div className="space-y-2"><div className={`flex items-center rounded-xl px-3 border ${field}`}><Search className="w-4 h-4 text-[#8696a0]"/><input value={query} onChange={event => { setQuery(event.target.value); setCreating(false); }} placeholder="Nome ou telefone" className="w-full bg-transparent px-2 py-2.5 text-xs outline-none"/>{searching && <Loader2 className="w-4 h-4 animate-spin"/>}</div>
    {(results.length > 0 || canCreate) && <div className="max-h-44 overflow-y-auto border border-current/10 rounded-xl">{results.map(contact => { const member = memberIds.has(contact.id) || members.has(digits(contact.phoneNumber)); return <button type="button" key={contact.id} disabled={selectedIds.has(contact.id) || member} onClick={() => onChange([...selected, contact])} className="w-full flex gap-3 items-center p-2 text-left hover:bg-black/5 disabled:opacity-50"><div className="w-8 h-8 rounded-full bg-[#00a884] text-white overflow-hidden flex items-center justify-center">{contact.avatarUrl ? <img src={contact.avatarUrl} alt="" className="w-full h-full object-cover"/> : (contact.name || contact.phoneNumber).slice(0, 1).toUpperCase()}</div><div><p className="text-xs font-semibold">{contact.name || contact.phoneNumber}</p><p className="text-[10px] text-[#8696a0]">{contact.phoneNumber}</p></div>{member ? <span className="ml-auto text-[10px] text-[#8696a0]">Já está no grupo</span> : selectedIds.has(contact.id) && <Check className="ml-auto w-4 h-4"/>}</button>; })}
      {canCreate && !creating && <button type="button" onClick={() => setCreating(true)} className="w-full flex items-center gap-2 p-3 text-xs font-semibold text-[#00a884]"><UserPlus className="w-4 h-4"/>+ Criar contato +{typedPhone}</button>}
    </div>}
    {creating && <div className={`rounded-xl border p-3 space-y-2 ${field}`}><label className="block text-xs">Nome<input autoFocus value={newName} onChange={event => setNewName(event.target.value)} className="mt-1 w-full rounded-lg border border-current/20 bg-transparent px-3 py-2"/></label><p className="text-xs text-[#8696a0]">Telefone: +{typedPhone}</p><div className="flex justify-end gap-2"><button type="button" onClick={() => setCreating(false)} className="px-3 py-2 text-xs">Cancelar</button><button type="button" disabled={!newName.trim() || searching} onClick={() => void create()} className="rounded-lg bg-[#00a884] px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Criar e selecionar</button></div></div>}
    {selected.length > 0 && <div className="flex flex-wrap gap-2">{selected.map(contact => <span key={contact.id} className="inline-flex items-center gap-1 px-2 py-1 rounded-full bg-[#00a884]/15 text-xs">{contact.name || contact.phoneNumber}<button type="button" onClick={() => onChange(selected.filter(item => item.id !== contact.id))}><X className="w-3 h-3"/></button></span>)}</div>}{error && <p className="text-xs text-red-500">{error}</p>}
  </div>;
};
