import { useEffect, useState } from 'react';
import { Check, Edit3, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import type { PermissionProfile } from '../domain/currentUser';
import { inboxService } from '../integrations/chatwoot/inboxes';
import { errorMessageForUser } from '../integrations/chatwoot/errors';

const INBOX = [['conversation_view_all', 'Visualizar todas as conversas'], ['conversation_view_assigned', 'Visualizar conversas atribuídas'], ['conversation_view_unassigned', 'Visualizar conversas não atribuídas'], ['conversation_take', 'Assumir conversas'], ['conversation_assign', 'Atribuir conversas'], ['conversation_reply', 'Responder mensagens'], ['conversation_status_priority', 'Alterar status e prioridade'], ['inbox_manage', 'Gerenciar completamente a inbox']] as const;
const SYSTEM = [['contacts_manage', 'Contatos'], ['labels_manage', 'Etiquetas'], ['canned_responses_manage', 'Respostas rápidas'], ['agents_manage', 'Agentes'], ['teams_manage', 'Equipes'], ['inboxes_manage', 'Inboxes'], ['integrations_manage', 'Aplicações e integrações'], ['audit_logs_view', 'Registros de auditoria'], ['account_settings_manage', 'Configurações da conta']] as const;

export const PermissionProfilesPanel = ({ accountId, isDarkMode }: { accountId: number | null; isDarkMode: boolean }) => {
  const [profiles, setProfiles] = useState<PermissionProfile[]>([]);
  const [editing, setEditing] = useState<PermissionProfile | null | 'new'>(null);
  const [form, setForm] = useState({ name: '', description: '', kind: 'inbox' as 'inbox' | 'system', inboxPermissions: [] as string[], systemPermissions: [] as string[] });
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const load = () => accountId && inboxService.listPermissionProfiles(accountId).then(setProfiles).catch(() => setError('Não foi possível carregar os perfis.'));
  useEffect(() => { void load(); }, [accountId]);
  const open = (profile: PermissionProfile | 'new', kind: 'inbox' | 'system' = 'inbox') => { setError(null); setEditing(profile); setForm(profile === 'new' ? { name: '', description: '', kind, inboxPermissions: [], systemPermissions: [] } : { name: profile.name, description: profile.description || '', kind: profile.kind, inboxPermissions: profile.inboxPermissions, systemPermissions: profile.systemPermissions }); };
  const toggle = (key: 'inboxPermissions' | 'systemPermissions', value: string) => setForm(current => ({ ...current, [key]: current[key].includes(value) ? current[key].filter(item => item !== value) : [...current[key], value] }));
  const save = async () => { if (!accountId || !form.name.trim()) return; setSaving(true); try { const saved = editing === 'new' ? await inboxService.createPermissionProfile(accountId, form) : await inboxService.updatePermissionProfile(accountId, editing!.id, form); setProfiles(current => editing === 'new' ? [...current, saved] : current.map(profile => profile.id === saved.id ? saved : profile)); setEditing(null); } catch (cause) { setError(errorMessageForUser(cause)); } finally { setSaving(false); } };
  const remove = async (profile: PermissionProfile) => { if (!accountId || profile.isDefault || !window.confirm(`Excluir o perfil ${profile.name}?`)) return; try { await inboxService.deletePermissionProfile(accountId, profile.id); setProfiles(current => current.filter(item => item.id !== profile.id)); } catch (cause) { setError(errorMessageForUser(cause)); } };
  const card = isDarkMode ? 'border-[#2a3942] bg-[#182228]' : 'border-[#d1d7db] bg-gray-50';
  return <section className={`p-6 rounded-2xl border shadow-xl space-y-5 ${isDarkMode ? 'bg-[#111b21] border-[#222d34]' : 'bg-white border-[#d1d7db]'}`}>
    <div className="border-b border-white/10 pb-4"><h3 className="text-lg font-bold flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-[#00a884]" />Perfis de permissão</h3><p className="mt-1 text-xs text-[#8696a0]">Perfis de inbox são aplicados por caixa; perfis gerais são aplicados uma única vez ao agente.</p></div>
    {error && <p className="text-xs text-red-400">{error}</p>}
    {(['inbox', 'system'] as const).map(kind => <section key={kind}><div className="mb-2 flex items-center justify-between"><div><h4 className="text-sm font-bold">{kind === 'inbox' ? 'Perfis de inbox' : 'Perfis gerais do sistema'}</h4><p className="text-[11px] text-[#8696a0]">{kind === 'inbox' ? 'Controlam apenas conversas e ações da caixa.' : 'Controlam recursos globais e não dependem da inbox.'}</p></div><button type="button" onClick={() => open('new', kind)} className="rounded-xl bg-[#00a884] px-3 py-2 text-xs font-bold text-white"><Plus className="inline w-4 h-4 mr-1" />Novo perfil</button></div><div className="space-y-2">{profiles.filter(profile => profile.kind === kind).map(profile => <div key={profile.id} className={`flex items-center justify-between rounded-xl border p-3 ${card}`}><div><p className="text-sm font-bold">{profile.name} {profile.isDefault && <span className="ml-2 text-[10px] text-[#00a884]">PADRÃO</span>}</p><p className="text-xs text-[#8696a0]">{profile.description || 'Sem descrição'} · {kind === 'inbox' ? `${profile.inboxPermissions.length} permissões de inbox` : `${profile.systemPermissions.length} permissões gerais`}</p></div><div className="flex gap-1"><button type="button" onClick={() => open(profile)} className="p-2 text-[#00a884]"><Edit3 className="w-4 h-4" /></button>{!profile.isDefault && <button type="button" onClick={() => void remove(profile)} className="p-2 text-red-400"><Trash2 className="w-4 h-4" /></button>}</div></div>)}</div></section>)}
    {editing && <div className="fixed inset-0 z-[120] grid place-items-center bg-black/70 p-4"><div className={`max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl p-5 shadow-2xl ${isDarkMode ? 'bg-[#202c33] text-[#e9edef]' : 'bg-white text-[#111b21]'}`}><h4 className="font-bold">{editing === 'new' ? 'Novo perfil' : 'Editar perfil'}</h4><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Nome" className={`mt-4 w-full rounded-lg border p-2 text-sm ${isDarkMode ? 'border-[#40515a] bg-[#111b21] text-white placeholder:text-[#8696a0]' : 'border-[#d1d7db] bg-white text-[#111b21]'}`} /><textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Descrição" className={`mt-2 w-full rounded-lg border p-2 text-sm ${isDarkMode ? 'border-[#40515a] bg-[#111b21] text-white placeholder:text-[#8696a0]' : 'border-[#d1d7db] bg-white text-[#111b21]'}`} />
      <p className="mt-4 text-xs text-[#9fb0ba]">Tipo: <strong className="text-[#e9edef]">{form.kind === 'inbox' ? 'Perfil de inbox' : 'Perfil geral do sistema'}</strong></p>{form.kind === 'inbox' ? <PermissionGroup isDarkMode={isDarkMode} title="Permissões por inbox" items={INBOX} values={form.inboxPermissions} onToggle={value => toggle('inboxPermissions', value)} /> : <PermissionGroup isDarkMode={isDarkMode} title="Permissões gerais" items={SYSTEM} values={form.systemPermissions} onToggle={value => toggle('systemPermissions', value)} />}
      <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setEditing(null)} className="px-3 py-2 text-xs">Cancelar</button><button type="button" disabled={saving} onClick={() => void save()} className="rounded-lg bg-[#00a884] px-4 py-2 text-xs font-bold text-white">{saving ? 'Salvando…' : 'Salvar'}</button></div></div></div>}
  </section>;
};

const PermissionGroup = ({ title, items, values, onToggle, isDarkMode }: { title: string; items: readonly (readonly [string, string])[]; values: string[]; onToggle: (value: string) => void; isDarkMode: boolean }) => <div className="mt-5"><p className="mb-2 text-xs font-bold">{title}</p><div className="grid gap-2 sm:grid-cols-2">{items.map(([value, label]) => <button type="button" key={value} onClick={() => onToggle(value)} className={`flex items-center gap-2 rounded-lg border p-2 text-left text-xs transition-colors ${values.includes(value) ? 'border-[#00a884] bg-[#00a884]/15 text-[#e9edef]' : isDarkMode ? 'border-[#40515a] bg-[#182228] text-[#d7e0e5] hover:border-[#8696a0]' : 'border-[#d1d7db] bg-gray-50 text-[#111b21]'}`}>{values.includes(value) && <Check className="w-3 h-3 text-[#00a884]" />}{label}</button>)}</div></div>;
